version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://your_postgres_username:your_postgres_password@postgres:5432/your_postgres_database_name
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_database_name
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:


